version: 2.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: /CfucRi5JIhmrcPoornr8fG/r+sRY4jETLdQqJlbxo/4rMMtfuKYI2TDeNu9gg+A
build_script:
- dotnet restore src\HtmlMinificationMiddleware\HtmlMinificationMiddleware.csproj 
- dotnet pack -c Release -o Output src\HtmlMinificationMiddleware\HtmlMinificationMiddleware.csproj
- dotnet restore Test\HtmlMinificationMiddlewareTests\HtmlMinificationMiddleware.Tests.csproj 
test_script:
- cmd: dotnet test C:\projects\HtmlMinificationMiddleware\Test\HtmlMinificationMiddlewareTests\HtmlMinificationMiddleware.Tests.csproj
artifacts:
- path: '\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: 5XsCPhzHSChTdym1nwcZps3YxhZqySNztlUeT1rWtMmvrDM+R+WzxUkrYiMLBUVs
    skip_symbols: true
